package com.fchen_group.TPDSInScf.Core;
/**
 *
 * This class is used to store challenge data,including two parts:coefficients and index
 * challenge data is generated by Client
 * */
public class ChallengeData {
    public byte[] coefficients;
    public int[] index;

    public ChallengeData(int [] index , byte[] coefficients){
        this.index = index;
        this.coefficients = coefficients;
    }
}
